# Generated by Django 2.0.7 on 2018-07-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allergen', '0004_auto_20180712_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='translations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allergen.Translation'),
        ),
    ]
