sudo: required

language: python

before_script:
    - docker-compose up

services:
    - postgresql
    - docker

env: DJANGO_SETTINGS_MODULE=allergen_project.settings.travis

after_success:
    - docker run web python manage.py tests
    - codecov
