sudo: required

language: python

services:
    - docker

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
    - docker version
    - docker-compose version

before_script:
    - docker build web
    - docker run web python manage.py migrate

script:
    - docker run web python manage.py tests

after_success:
    - codecov
