language: python

python:
    - '3.7-dev'

before_script:
    - pip install pipenv
    - pipenv install --three

services:
    - postgresql

env: DJANGO_SETTINGS_MODULE=allergen.settings.travis

script:
    - ./manage.py test

after_success:
  - codecov
