sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - pwd
  - ls -l
  - docker --version
  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker-compose up

script:
  - docker-compose run django coverage run ./manage.py test
  - docker-compose run django coverage report
  - docker-compose run django coverage xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
