sudo: required

language: python

services:
    - docker

addons:
  apt:
    packages:
      - docker-ce

script:
    - docker version
    - docker-compose version

before_script:
    - sudo docker-compose up


script:
    - sudo docker run allergen_web python manage.py tests

after_script:
    - docker-compose down

after_success:
    - codecov
