sudo: required

language: python

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
  - docker-compose up --build

script:
  - docker-compose run django coverage run ./manage.py test
  - docker-compose run django coverage report
  - docker-compose run django coverage xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
