# Generated by Django 2.0.7 on 2018-07-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergen', '0005_product_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='translations',
        ),
    ]
